[project]
name = "server"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.proxy]
path = "contracts/proxy.clar"
depends_on = []
